services:
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
